AllowedDrops:
  - BONE
  - ARROW
  - ROTTEN_FLESH
  - COAL
  - IRON_INGOT

Collector:
  Material: BEACON
  Title: "&e&lCHUNK COLLECTOR"
  Lore: [ ]
  Hologram:
    - "&8&m------------"
    - "&e&lCHUNK COLLECTOR"
    - "&8&m------------"

BackButton:
  Material: BARRIER
  Title: "&c&lBACK"
  Lore: [ ]


CollectorMenu:
  Title: "&fMenu"
  Size: 27
  Drops:
    Title: "&f| &e&lDrops"
    Material: DIAMOND
    Lore: [ ]
    Slot: 12
  Upgrades:
    Title: "&f| &b&lUpgrades"
    Material: EXPERIENCE_BOTTLE
    Lore: [ ]
    Slot: 14
  Barrier:
    Title: "&f| &b&lBarrier"
    Material: BARRIER
    Lore: [ ]
    Slot: 26

  DropsMenu:
    Title: "&fMenu"
    Size: 27
    GenericTitle: "&8» %type%"
    GenericLore:
      - "&fClick me to sell all!"
      - "&eAmount &7» &f%amount%"
      - "&eMoney &7» &f%price%"

  UpgradeMenu:
    Title: "&fMenu"
    Size: 27
    SellMultiItem:
      Title: "&eSell Multiplier Upgrade"
      Material: DIAMOND
      Lore:
        - "&eCurrent Level &7» &f%level%"
        - "&eCurrent Multi &7» &f%multi%"
        - ""
        - "&eNext Multi &7» &f%next_multi%"
        - "&eCost &f» &f%cost%"
      Slot: 10
    ChunkSizeItem:
      Title: "&eChunk Size Upgrade"
      Material: STONE
      Lore:
        - "&a"
        - "line2"
        - "line3"
      Slot: 12
    CapacitySizeItem:
      Title: "&eCapacity Upgrade"
      Material: STONE
      Lore:
        - "&a"
        - "line1"
        - "line2"
      Slot: 14

Upgrades:
  SellMulti:
    1:
      Multi: 1
      Cost: 0
    2:
      Multi: 1.2
      Cost: 1000
    3:
      Multi: 1.3
      Cost: 5000
    4:
      Multi: 1.4
      Cost: 6000
    5:
      Multi: 1.5
      Cost: 8000
  Capacity:
    1:
      Capacity: 5000
      Cost: 1000
    2:
      Capacity: 10000
      Cost: 1000
    3:
      Capacity: 30000
      Cost: 1000
    4:
      Capacity: 20000
      Cost: 1000
  Chunks:
    1:
      Radius: 0 #Only The Chunk The Collector Is In
      Cost: 1000
    2:
      Radius: 1 #Circle Around The Starting chunk so kinda like this visual...
      Cost: 1000
    # 111
    # 121 With 2 Being the Chunk the Collector is in
    # 111
    3:
      Radius: 2
      Cost: 1000
    #11111
    #11111
    #11211
    #11111
    #11111